// Import necessary functions from Redux Toolkit Query
import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

// Create an API using createApi from Redux Toolkit Query
const authApi = createApi({
  // Configuration options for the API
  reducerPath: "authApi", // A name for the slice of state for this API
  baseQuery: fetchBaseQuery({
    baseUrl: "https://redmangoapi.azurewebsites.net/api/", // Base URL for API requests
  }),

  endpoints: (builder) => ({
    // Define API endpoints using builder
    registerUser: builder.mutation({
      query: (userData) => ({
        url: "auth/register",
        method: "POST",
        headers: {
          "Content-type": "application/json",
        },
        body: userData,
      }),
    }),

    // Fixed syntax: Separate loginUser from the registerUser definition
    loginUser: builder.mutation({
      query: (userCredentials) => ({
        url: "auth/login",
        method: "POST",
        headers: {
          "Content-type": "application/json",
        },
        body: userCredentials,
      }),
    }),
  }),
});

// Extract query hooks generated by createApi for each endpoint
export const { useRegisterUserMutation, useLoginUserMutation } = authApi;

// Export the configured API
export default authApi;
