// Import necessary functions from Redux Toolkit Query
import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

// Create an API using createApi from Redux Toolkit Query
const paymentApi = createApi({
  // Configuration options for the API
  reducerPath: "paymentApi", // A name for the slice of state for this API
  baseQuery: fetchBaseQuery({
    baseUrl: "https://redmangoapi.azurewebsites.net/api/", // Base URL for API requests
    prepareHeaders: (headers: Headers, api) => {
      const token = localStorage.getItem("token");
      token && headers.append("Authorization", "Bearer " + token);
    },
  }),

  endpoints: (builder) => ({
    // Define API endpoints using builder
    initiatePayment: builder.mutation({
      // Endpoint for initiating payment
      query: (userId) => ({
        url: "payment", // API endpoint URL
        method: "POST",
        params: {
          userId: userId,
        },
      }),
    }),
  }),
});

// Extract query hooks generated by createApi for each endpoint
export const { useInitiatePaymentMutation } = paymentApi;

// Export the configured API
export default paymentApi;
